<link href="<?php echo $this->getSkinUrl();?>ship/css/jquery.autoSuggest.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl();?>ship/js/jquery-1.11.0.js"></script>
<script type="text/javascript">jQuery.noConflict();</script>
<script type="text/javascript" src="https://www.transdirect.com.au/api/locations/script"></script>
<script src="<?php echo $this->getSkinUrl();?>ship/js/jquery.autoSuggest.js"></script>